"""Static physics content for the Mechanics module: topics, simulations, experiments, practice questions."""

TOPICS = [
    {
        "id": "mechanics",
        "name": "Mechanics",
        "tagline": "Motion, forces, energy & momentum",
        "color": "#2563EB",
        "concepts": 11,
        "status": "live",
    },
    {"id": "electricity", "name": "Electricity", "tagline": "Circuits, current & fields", "color": "#F59E0B", "concepts": 0, "status": "soon"},
    {"id": "optics", "name": "Optics", "tagline": "Light, lenses & interference", "color": "#8B5CF6", "concepts": 0, "status": "soon"},
    {"id": "thermodynamics", "name": "Thermodynamics", "tagline": "Heat, entropy & engines", "color": "#EF4444", "concepts": 0, "status": "soon"},
    {"id": "waves", "name": "Waves", "tagline": "Oscillations & sound", "color": "#10B981", "concepts": 0, "status": "soon"},
    {"id": "modern", "name": "Modern Physics", "tagline": "Quantum & relativity", "color": "#0EA5E9", "concepts": 0, "status": "soon"},
]

SIMULATIONS = [
    {
        "id": "projectile",
        "title": "Projectile Motion",
        "topic": "mechanics",
        "difficulty": "Beginner",
        "summary": "Launch a projectile and study its parabolic path under gravity, drag and wind.",
        "concepts": ["Kinematics", "Vectors", "Air resistance"],
        "equation": "R = \\frac{v_0^2 \\sin(2\\theta)}{g}",
    },
    {
        "id": "pendulum",
        "title": "Simple Pendulum",
        "topic": "mechanics",
        "difficulty": "Beginner",
        "summary": "Explore oscillations, time period and the effect of length, gravity and damping.",
        "concepts": ["SHM", "Time period", "Damping"],
        "equation": "T = 2\\pi\\sqrt{\\frac{L}{g}}",
    },
    {
        "id": "collision",
        "title": "1D Collisions",
        "topic": "mechanics",
        "difficulty": "Intermediate",
        "summary": "Collide two masses and observe conservation of momentum and energy.",
        "concepts": ["Momentum", "Elasticity", "Energy"],
        "equation": "m_1u_1 + m_2u_2 = m_1v_1 + m_2v_2",
    },
    {
        "id": "spring",
        "title": "Mass-Spring Oscillator",
        "topic": "mechanics",
        "difficulty": "Intermediate",
        "summary": "Study simple harmonic motion of a mass on a spring with adjustable stiffness.",
        "concepts": ["Hooke's law", "SHM", "Resonance"],
        "equation": "T = 2\\pi\\sqrt{\\frac{m}{k}}",
    },
    {
        "id": "orbit",
        "title": "Gravity & Orbits",
        "topic": "mechanics",
        "difficulty": "Advanced",
        "summary": "Set a satellite's velocity and watch it orbit, escape or crash under gravity.",
        "concepts": ["Gravitation", "Orbital velocity", "Energy"],
        "equation": "v_{orbit} = \\sqrt{\\frac{GM}{r}}",
    },
    {
        "id": "incline",
        "title": "Inclined Plane",
        "topic": "mechanics",
        "difficulty": "Beginner",
        "summary": "Slide a block down a ramp and study friction, normal force and acceleration.",
        "concepts": ["Friction", "Newton's laws", "Free body"],
        "equation": "a = g(\\sin\\theta - \\mu\\cos\\theta)",
    },
    {
        "id": "pulley",
        "title": "Pulley System (Atwood)",
        "topic": "mechanics",
        "difficulty": "Intermediate",
        "summary": "Connect two masses over a pulley and explore acceleration and string tension.",
        "concepts": ["Newton's laws", "Tension", "Constraint"],
        "equation": "a = \\frac{(m_1-m_2)g}{m_1+m_2}",
    },
    {
        "id": "banked",
        "title": "Banked Curve",
        "topic": "mechanics",
        "difficulty": "Advanced",
        "summary": "Drive a car around a banked turn and find the safe speed range before it skids.",
        "concepts": ["Circular motion", "Friction", "Centripetal force"],
        "equation": "v_{ideal} = \\sqrt{g\\,r\\,\\tan\\theta}",
    },
    {
        "id": "energyramp",
        "title": "Energy Skate Ramp",
        "topic": "mechanics",
        "difficulty": "Intermediate",
        "summary": "Watch kinetic and potential energy trade off on a curved track and see conservation live.",
        "concepts": ["Energy conservation", "KE & PE", "Friction"],
        "equation": "\\tfrac{1}{2}mv^2 + mgh = \\text{const}",
    },
    {
        "id": "conical",
        "title": "Conical Pendulum",
        "topic": "mechanics",
        "difficulty": "Advanced",
        "summary": "Spin a bob in a horizontal circle and relate cone angle, period and string tension.",
        "concepts": ["Circular motion", "Tension", "Time period"],
        "equation": "T = 2\\pi\\sqrt{\\frac{L\\cos\\theta}{g}}",
    },
    {
        "id": "verticalloop",
        "title": "Vertical Loop",
        "topic": "mechanics",
        "difficulty": "Advanced",
        "summary": "Send a ball around a vertical loop and find the minimum speed to keep contact at the top.",
        "concepts": ["Circular motion", "Energy", "Critical speed"],
        "equation": "v_{top} \\geq \\sqrt{gr}",
    },
]

EXPERIMENTS = [
    {
        "id": "exp-pendulum-g",
        "title": "Measure g using a Simple Pendulum",
        "topic": "mechanics",
        "objective": "To determine the acceleration due to gravity (g) by measuring the time period of a simple pendulum for various lengths.",
        "equipment": ["Pendulum bob", "Inextensible string", "Stopwatch", "Meter scale", "Clamp stand"],
        "theory": "For a simple pendulum, T = 2\\pi\\sqrt{L/g}. Plotting T^2 against L gives a straight line of slope 4\\pi^2/g.",
        "sim": "pendulum",
        "record_columns": ["Length L (m)", "Time for 10 osc. (s)", "Period T (s)", "T² (s²)"],
        "expected_g": 9.8,
    },
    {
        "id": "exp-spring-k",
        "title": "Hooke's Law: Spring Constant",
        "topic": "mechanics",
        "objective": "To verify Hooke's law and determine the spring constant k from the extension produced by known masses.",
        "equipment": ["Helical spring", "Slotted masses", "Meter scale", "Clamp stand", "Pointer"],
        "theory": "By Hooke's law F = kx. The slope of a Force vs Extension graph gives the spring constant k.",
        "sim": "spring",
        "record_columns": ["Mass m (kg)", "Force F (N)", "Extension x (m)"],
        "expected_k": 20.0,
    },
]

PRACTICE_QUESTIONS = [
    {"id": "q1", "topic": "kinematics", "difficulty": "easy", "type": "mcq",
     "question": "A body is thrown vertically upward with velocity 20 m/s. The maximum height reached is (g = 10 m/s²):",
     "options": ["10 m", "20 m", "40 m", "5 m"], "answer": 1, "solution": "H = u²/2g = 400/20 = 20 m."},
    {"id": "q2", "topic": "projectile", "difficulty": "easy", "type": "mcq",
     "question": "The horizontal range of a projectile is maximum when the angle of projection is:",
     "options": ["30°", "45°", "60°", "90°"], "answer": 1, "solution": "Range ∝ sin(2θ), maximum when 2θ = 90°, i.e. θ = 45°."},
    {"id": "q3", "topic": "newton", "difficulty": "medium", "type": "numerical",
     "question": "A 2 kg block is pushed with 10 N on a frictionless surface. Find its acceleration in m/s².",
     "answer": 5.0, "tolerance": 0.1, "solution": "a = F/m = 10/2 = 5 m/s²."},
    {"id": "q4", "topic": "momentum", "difficulty": "medium", "type": "mcq",
     "question": "Two equal masses collide head-on elastically with equal and opposite velocities. After collision they:",
     "options": ["stick together", "exchange velocities", "stop", "move faster"], "answer": 1,
     "solution": "In elastic collision of equal masses, velocities are exchanged."},
    {"id": "q5", "topic": "energy", "difficulty": "hard", "type": "numerical",
     "question": "A 0.5 kg mass on a spring (k = 200 N/m) is displaced 0.1 m. Find max KE in Joules.",
     "answer": 1.0, "tolerance": 0.05, "solution": "Max KE = ½kA² = 0.5×200×0.01 = 1 J."},
    {"id": "q6", "topic": "gravitation", "difficulty": "hard", "type": "mcq",
     "question": "The orbital velocity of a satellite close to Earth's surface is approximately:",
     "options": ["7.9 km/s", "11.2 km/s", "3.0 km/s", "5.6 km/s"], "answer": 0,
     "solution": "v = √(gR) ≈ 7.9 km/s (first cosmic velocity)."},
    {"id": "q7", "topic": "kinematics", "difficulty": "easy", "type": "numerical",
     "question": "A car accelerates uniformly from rest to 20 m/s in 4 s. Find acceleration in m/s².",
     "answer": 5.0, "tolerance": 0.1, "solution": "a = (v-u)/t = 20/4 = 5 m/s²."},
    {"id": "q8", "topic": "projectile", "difficulty": "medium", "type": "numerical",
     "question": "A ball is projected at 20 m/s at 30°. Find its time of flight in seconds (g = 10).",
     "answer": 2.0, "tolerance": 0.1, "solution": "T = 2u sinθ/g = 2×20×0.5/10 = 2 s."},
    {"id": "q9", "topic": "shm", "difficulty": "medium", "type": "mcq",
     "question": "The time period of a simple pendulum depends on:",
     "options": ["Mass of bob", "Amplitude (small)", "Length & g", "Material of string"], "answer": 2,
     "solution": "T = 2π√(L/g) — depends only on length and g for small oscillations."},
    {"id": "q10", "topic": "energy", "difficulty": "hard", "type": "mcq",
     "question": "A body slides down a frictionless incline of height h. Its speed at the bottom is:",
     "options": ["√(gh)", "√(2gh)", "2gh", "gh"], "answer": 1,
     "solution": "Energy conservation: mgh = ½mv² ⟹ v = √(2gh)."},
]