"""Static physics content for the Mechanics module: topics, simulations, experiments, practice questions."""

TOPICS = [
    {
        "id": "mechanics",
        "name": "Mechanics",
        "tagline": "Motion, forces, energy & momentum",
        "color": "#2563EB",
        "concepts": 11,
        "status": "live",
    },
    {"id": "electricity", "name": "Electricity", "tagline": "Circuits, current & fields", "color": "#F59E0B", "concepts": 0, "status": "soon"},
    {"id": "optics", "name": "Optics", "tagline": "Light, lenses & interference", "color": "#8B5CF6", "concepts": 0, "status": "soon"},
    {"id": "thermodynamics", "name": "Thermodynamics", "tagline": "Heat, entropy & engines", "color": "#EF4444", "concepts": 0, "status": "soon"},
    {"id": "waves", "name": "Waves", "tagline": "Oscillations & sound", "color": "#10B981", "concepts": 0, "status": "soon"},
    {"id": "modern", "name": "Modern Physics", "tagline": "Quantum & relativity", "color": "#0EA5E9", "concepts": 0, "status": "soon"},
]

SIMULATIONS = [
    {
        "id": "projectile",
        "title": "Projectile Motion",
        "topic": "mechanics",
        "difficulty": "Beginner",
        "summary": "Launch a projectile and study its parabolic path under gravity, drag and wind.",
        "concepts": ["Kinematics", "Vectors", "Air resistance"],
        "equation": "R = \\frac{v_0^2 \\sin(2\\theta)}{g}",
    },
    {
        "id": "periodicmotion",
        "title": "Periodic Motion",
        "topic": "mechanics",
        "difficulty": "Beginner",
        "summary": "Examine fundamental relationships of periodic motion: time period T = 1/f, frequency f = 1/T, and uniform circular reference projection.",
        "concepts": ["Periodic Motion", "Frequency", "Time Period", "Phasor"],
        "equation": "T = \\frac{1}{f} \\qquad f = \\frac{1}{T} \\qquad \\omega = 2\\pi f",
    },
    {
        "id": "shm",
        "title": "Simple Harmonic Motion (SHM)",
        "topic": "mechanics",
        "difficulty": "Beginner",
        "summary": "Simulate linear SHM with exact kinematic relationships: x(t) = A cos(ωt + φ), v(t) = -Aω sin(ωt + φ), and a(t) = -ω²x.",
        "concepts": ["SHM", "Displacement", "Velocity", "Acceleration"],
        "equation": "x(t) = A\\cos(\\omega t + \\phi) \\qquad v(t) = -A\\omega\\sin(\\omega t + \\phi) \\qquad a(t) = -\\omega^2 x",
    },
    {
        "id": "pendulum",
        "title": "Simple Pendulum",
        "topic": "mechanics",
        "difficulty": "Beginner",
        "summary": "Simulate a simple pendulum with exact non-linear rotational dynamics, string tension, restoring torque, and small-angle comparison.",
        "concepts": ["Pendulum", "Time Period", "Restoring Torque", "Tension"],
        "equation": "T = 2\\pi\\sqrt{\\frac{L}{g}} \\qquad \\frac{d^2\\theta}{dt^2} + \\frac{g}{L}\\sin\\theta = 0",
    },
    {
        "id": "spring",
        "title": "Mass-Spring Oscillator",
        "topic": "mechanics",
        "difficulty": "Intermediate",
        "summary": "Simulate a mass on a spring adhering to Hooke's Law F = -kx with exact natural frequency ω = √(k/m) and time period T = 2π√(m/k).",
        "concepts": ["Hooke's Law", "Spring Constant", "Natural Frequency", "Restoring Force"],
        "equation": "F = -kx \\qquad \\omega = \\sqrt{\\frac{k}{m}} \\qquad T = 2\\pi\\sqrt{\\frac{m}{k}}",
    },
    {
        "id": "energyshm",
        "title": "Energy in SHM",
        "topic": "mechanics",
        "difficulty": "Intermediate",
        "summary": "Track continuous interchange between kinetic energy KE = ½mv² and potential energy PE = ½kx², proving total mechanical energy E = ½kA² remains constant.",
        "concepts": ["Energy Conservation", "Kinetic Energy", "Potential Energy", "Potential Well"],
        "equation": "E = \\tfrac{1}{2}kA^2 \\qquad KE = \\tfrac{1}{2}mv^2 \\qquad PE = \\tfrac{1}{2}kx^2",
    },
    {
        "id": "damping",
        "title": "Damped Oscillations",
        "topic": "mechanics",
        "difficulty": "Intermediate",
        "summary": "Explore damped harmonic motion m x'' + c x' + kx = 0 across underdamped, critically damped, and overdamped regimes with exponential decay envelopes.",
        "concepts": ["Damping", "Underdamped", "Critical Damping", "Overdamped", "Decay Envelope"],
        "equation": "x(t) = A_0 e^{-\\beta t}\\cos(\\omega_d t + \\phi) \\qquad \\beta = \\frac{c}{2m}",
    },
    {
        "id": "resonance",
        "title": "Forced Oscillations & Resonance",
        "topic": "mechanics",
        "difficulty": "Advanced",
        "summary": "Simulate a driven damped oscillator m x'' + c x' + kx = F₀ cos(ωt) and observe steady-state amplitude peak at resonance frequency ω ≈ ω₀.",
        "concepts": ["Forced Oscillations", "Resonance", "Quality Factor", "Phase Lag"],
        "equation": "A(\\omega) = \\frac{F_0/m}{\\sqrt{(\\omega_0^2 - \\omega^2)^2 + (2\\beta\\omega)^2}}",
    },
    {
        "id": "collision",
        "title": "1D Collisions",
        "topic": "mechanics",
        "difficulty": "Intermediate",
        "summary": "Collide two masses and observe conservation of momentum and energy.",
        "concepts": ["Momentum", "Elasticity", "Energy"],
        "equation": "m_1u_1 + m_2u_2 = m_1v_1 + m_2v_2",
    },
    {
        "id": "gravitationlaw",
        "title": "Universal Law of Gravitation",
        "topic": "mechanics",
        "difficulty": "Beginner",
        "summary": "Explore Newton's Universal Law of Gravitation: mutual gravitational attraction between two masses as a function of distance.",
        "concepts": ["Universal Gravitation", "Inverse Square Law", "Newton's Third Law"],
        "equation": "F = G\\frac{M_1 M_2}{r^2}",
    },
    {
        "id": "gravfield",
        "title": "Gravitational Field",
        "topic": "mechanics",
        "difficulty": "Intermediate",
        "summary": "Visualize gravitational field intensity vectors g = GM/r² around a planet at various altitudes.",
        "concepts": ["Gravitational Field", "Acceleration due to gravity", "Field Vectors"],
        "equation": "g = \\frac{GM}{r^2}",
    },
    {
        "id": "gravpotential",
        "title": "Gravitational Potential",
        "topic": "mechanics",
        "difficulty": "Intermediate",
        "summary": "Investigate gravitational potential V = -GM/r and potential energy U = -GMm/r relative to zero at infinity.",
        "concepts": ["Gravitational Potential", "Potential Energy", "Potential Well"],
        "equation": "V = -\\frac{GM}{r}",
    },
    {
        "id": "escapevelocity",
        "title": "Escape Velocity",
        "topic": "mechanics",
        "difficulty": "Advanced",
        "summary": "Simulate projectile launch from a planet's surface and determine whether it escapes or falls back based on v_e = √(2GM/R).",
        "concepts": ["Escape Velocity", "Specific Energy", "Binding Energy"],
        "equation": "v_e = \\sqrt{\\frac{2GM}{R}}",
    },
    {
        "id": "orbitalvelocity",
        "title": "Orbital Velocity",
        "topic": "mechanics",
        "difficulty": "Advanced",
        "summary": "Analyze circular orbital speed v_orbit = √(GM/r) and transition between sub-orbital, circular, elliptical, and escape trajectories.",
        "concepts": ["Orbital Velocity", "Circular Orbits", "Orbital Period"],
        "equation": "v_{\\text{orbit}} = \\sqrt{\\frac{GM}{r}}",
    },
    {
        "id": "satellites",
        "title": "Satellites & Orbital Mechanics",
        "topic": "mechanics",
        "difficulty": "Advanced",
        "summary": "Simulate real Earth satellite constellations (ISS, GPS, Geostationary) and observe ground track synchronization and orbital periods.",
        "concepts": ["Satellites", "Geostationary Orbit", "Centripetal Acceleration"],
        "equation": "T = 2\\pi\\sqrt{\\frac{(R+h)^3}{GM}}",
    },
    {
        "id": "kepler",
        "title": "Kepler's Laws of Planetary Motion",
        "topic": "mechanics",
        "difficulty": "Advanced",
        "summary": "Explore Kepler's three laws: elliptical orbits (1st), equal areas in equal times (2nd), and harmonic law T² ∝ a³ (3rd).",
        "concepts": ["Kepler's 1st Law", "Kepler's 2nd Law", "Kepler's 3rd Law"],
        "equation": "r(\\theta) = \\frac{a(1-e^2)}{1+e\\cos\\theta}",
    },
    {
        "id": "orbit",
        "title": "Gravity & Orbits",
        "topic": "mechanics",
        "difficulty": "Advanced",
        "summary": "Comprehensive orbital mechanics simulator with velocity Verlet numerical integration, dynamic energy conservation, and force/velocity vectors.",
        "concepts": ["Gravitation", "Orbital Velocity", "Energy Conservation"],
        "equation": "\\vec{a} = -\\frac{GM}{r^3}\\vec{r}",
    },
    {
        "id": "incline",
        "title": "Inclined Plane",
        "topic": "mechanics",
        "difficulty": "Beginner",
        "summary": "Slide a block down a ramp and study friction, normal force and acceleration.",
        "concepts": ["Friction", "Newton's laws", "Free body"],
        "equation": "a = g(\\sin\\theta - \\mu\\cos\\theta)",
    },
    {
        "id": "pulley",
        "title": "Pulley System (Atwood)",
        "topic": "mechanics",
        "difficulty": "Intermediate",
        "summary": "Connect two masses over a pulley and explore acceleration and string tension.",
        "concepts": ["Newton's laws", "Tension", "Constraint"],
        "equation": "a = \\frac{(m_1-m_2)g}{m_1+m_2}",
    },
    {
        "id": "banked",
        "title": "Banked Curve",
        "topic": "mechanics",
        "difficulty": "Advanced",
        "summary": "Drive a car around a banked turn and find the safe speed range before it skids.",
        "concepts": ["Circular motion", "Friction", "Centripetal force"],
        "equation": "v_{ideal} = \\sqrt{g\\,r\\,\\tan\\theta}",
    },
    {
        "id": "energyramp",
        "title": "Energy Skate Ramp",
        "topic": "mechanics",
        "difficulty": "Intermediate",
        "summary": "Watch kinetic and potential energy trade off on a curved track and see conservation live.",
        "concepts": ["Energy conservation", "KE & PE", "Friction"],
        "equation": "\\tfrac{1}{2}mv^2 + mgh = \\text{const}",
    },
    {
        "id": "conical",
        "title": "Conical Pendulum",
        "topic": "mechanics",
        "difficulty": "Advanced",
        "summary": "Spin a bob in a horizontal circle and relate cone angle, period and string tension.",
        "concepts": ["Circular motion", "Tension", "Time period"],
        "equation": "T = 2\\pi\\sqrt{\\frac{L\\cos\\theta}{g}}",
    },
    {
        "id": "verticalloop",
        "title": "Vertical Loop",
        "topic": "mechanics",
        "difficulty": "Advanced",
        "summary": "Send a ball around a vertical loop and find the minimum speed to keep contact at the top.",
        "concepts": ["Circular motion", "Energy", "Critical speed"],
        "equation": "v_{top} \\geq \\sqrt{gr}",
    },
]

EXPERIMENTS = [
    {
        "id": "exp-pendulum-g",
        "title": "Measure g using a Simple Pendulum",
        "topic": "mechanics",
        "objective": "To determine the acceleration due to gravity (g) by measuring the time period of a simple pendulum for various lengths.",
        "equipment": ["Pendulum bob", "Inextensible string", "Stopwatch", "Meter scale", "Clamp stand"],
        "theory": "For a simple pendulum, T = 2\\pi\\sqrt{L/g}. Plotting T^2 against L gives a straight line of slope 4\\pi^2/g.",
        "sim": "pendulum",
        "record_columns": ["Length L (m)", "Time for 10 osc. (s)", "Period T (s)", "T² (s²)"],
        "expected_g": 9.8,
    },
    {
        "id": "exp-spring-k",
        "title": "Hooke's Law: Spring Constant",
        "topic": "mechanics",
        "objective": "To verify Hooke's law and determine the spring constant k from the extension produced by known masses.",
        "equipment": ["Helical spring", "Slotted masses", "Meter scale", "Clamp stand", "Pointer"],
        "theory": "By Hooke's law F = kx. The slope of a Force vs Extension graph gives the spring constant k.",
        "sim": "spring",
        "record_columns": ["Mass m (kg)", "Force F (N)", "Extension x (m)"],
        "expected_k": 20.0,
    },
]

PRACTICE_QUESTIONS = [
    {"id": "q1", "topic": "kinematics", "difficulty": "easy", "type": "mcq",
     "question": "A body is thrown vertically upward with velocity 20 m/s. The maximum height reached is (g = 10 m/s²):",
     "options": ["10 m", "20 m", "40 m", "5 m"], "answer": 1, "solution": "H = u²/2g = 400/20 = 20 m."},
    {"id": "q2", "topic": "projectile", "difficulty": "easy", "type": "mcq",
     "question": "The horizontal range of a projectile is maximum when the angle of projection is:",
     "options": ["30°", "45°", "60°", "90°"], "answer": 1, "solution": "Range ∝ sin(2θ), maximum when 2θ = 90°, i.e. θ = 45°."},
    {"id": "q3", "topic": "newton", "difficulty": "medium", "type": "numerical",
     "question": "A 2 kg block is pushed with 10 N on a frictionless surface. Find its acceleration in m/s².",
     "answer": 5.0, "tolerance": 0.1, "solution": "a = F/m = 10/2 = 5 m/s²."},
    {"id": "q4", "topic": "momentum", "difficulty": "medium", "type": "mcq",
     "question": "Two equal masses collide head-on elastically with equal and opposite velocities. After collision they:",
     "options": ["stick together", "exchange velocities", "stop", "move faster"], "answer": 1,
     "solution": "In elastic collision of equal masses, velocities are exchanged."},
    {"id": "q5", "topic": "energy", "difficulty": "hard", "type": "numerical",
     "question": "A 0.5 kg mass on a spring (k = 200 N/m) is displaced 0.1 m. Find max KE in Joules.",
     "answer": 1.0, "tolerance": 0.05, "solution": "Max KE = ½kA² = 0.5×200×0.01 = 1 J."},
    {"id": "q6", "topic": "gravitation", "difficulty": "hard", "type": "mcq",
     "question": "The orbital velocity of a satellite close to Earth's surface is approximately:",
     "options": ["7.9 km/s", "11.2 km/s", "3.0 km/s", "5.6 km/s"], "answer": 0,
     "solution": "v = √(gR) ≈ 7.9 km/s (first cosmic velocity)."},
    {"id": "q7", "topic": "kinematics", "difficulty": "easy", "type": "numerical",
     "question": "A car accelerates uniformly from rest to 20 m/s in 4 s. Find acceleration in m/s².",
     "answer": 5.0, "tolerance": 0.1, "solution": "a = (v-u)/t = 20/4 = 5 m/s²."},
    {"id": "q8", "topic": "projectile", "difficulty": "medium", "type": "numerical",
     "question": "A ball is projected at 20 m/s at 30°. Find its time of flight in seconds (g = 10).",
     "answer": 2.0, "tolerance": 0.1, "solution": "T = 2u sinθ/g = 2×20×0.5/10 = 2 s."},
    {"id": "q9", "topic": "shm", "difficulty": "medium", "type": "mcq",
     "question": "The time period of a simple pendulum depends on:",
     "options": ["Mass of bob", "Amplitude (small)", "Length & g", "Material of string"], "answer": 2,
     "solution": "T = 2π√(L/g) — depends only on length and g for small oscillations."},
    {"id": "q10", "topic": "energy", "difficulty": "hard", "type": "mcq",
     "question": "A body slides down a frictionless incline of height h. Its speed at the bottom is:",
     "options": ["√(gh)", "√(2gh)", "2gh", "gh"], "answer": 1,
     "solution": "Energy conservation: mgh = ½mv² ⟹ v = √(2gh)."},
]
